Repository nodeshift/opossum, pull requests merged in 2018-03, with the labels that each got.

#140 feat: allow multiple circuits to aggregate stats
  examples/hystrix/README.md
  examples/hystrix/app.js
  examples/hystrix/hystrix-stream.js
  examples/hystrix/package-lock.json
  examples/jquery/app.js
  examples/jquery/index.js
  examples/react/server.js
  examples/seneca/app.js
  examples/seneca/index.js
  index.js
  lib/hystrix-formatter.js
  lib/hystrix-stats.js
  package-lock.json
  package.json
  test/hystrix-test.js
Labels: enhancement, needs-review, review, semver-minor

#159 build: upgrading to webpack 4x
  config/webpack.config.js
  package-lock.json
  package.json
Labels: in progress, review

#160 feat: add enable/disable for a circuit
  lib/circuit-helpers.js
  lib/circuit.js
  lib/symbols.js
  test/enable-disable-test.js
Labels: enhancement, in progress, review, semver-minor

#171 chore(source): typos and wrong args number on fallback function usage
  config/webpack.config.js
  lib/circuit.js
  lib/hystrix-formatter.js
  lib/hystrix-stats.js
  lib/status.js
Labels: in progress, review
