Repository nodeshift/opossum, pull requests merged in 2018-06, with the labels that each got.

#202 feat: optional timeout (#200)
  lib/circuit.js
Labels: enhancement, in progress

#209 chore(package): update webpack to version 4.12.0
  package.json
Labels: in progress, review

#211 chore(package): update webpack-cli to version 3.0.3
  package.json
Labels: review

#210 chore(package): update nyc to version 12.0.2
  package.json
Labels: in progress, review
