Repository nodeshift/opossum, pull requests merged in 2018-10, with the labels that each got.

#234 #223: added refrence to typings in docs
  README.md
Labels: in progress

#236 feat: add options.volumeThreshold
  index.js
  lib/circuit.js
  test/volume-threshold-test.js
Labels: enhancement, needs-review, review

#240 test: increase timeout value for testing
  test/test.js
Labels: tests
