Repository nodeshift/opossum, pull requests merged in 2018-05, with the labels that each got.

#189 test: ensure all tests are run in the browser
  config/webpack.config.js
  test/browser/index.js
Labels: review

#193 Fix Hapi link
  README.md
Labels: in progress

#197 feat: pass error as parameter to fallback function
  lib/circuit.js
  test/test.js
Labels: in progress

#201 fix: avoid calling fallback function twice (#198)
  lib/circuit.js
  test/test.js
Labels: bug, in progress

#204 chore(package): update webpack to version 4.10.1
  package.json
Labels: in progress, review

#203 Updated README file in JQuery example
  examples/jquery/README.md
Labels: docs, in progress
