Repository nodeshift/opossum, pull requests merged in 2022-09, with the labels that each got.

#671 chore: remove the options.maxFailures condition check
  README.md
  lib/circuit.js
Labels: code-quality

#674 feat: adds `AbortController` support
  README.md
  lib/circuit.js
  test/test.js
Labels: enhancement

#666 [Snyk] Upgrade serve from 13.0.2 to 13.0.4
  package-lock.json
  package.json
Labels: status/no-pr-activity

#654 [Snyk] Upgrade husky from 7.0.4 to 8.0.0
  package-lock.json
  package.json
Labels: status/no-pr-activity
